"""tablas_iniciales

Revision ID: 048e645f18dd
Revises: 
Create Date: 2026-04-05 13:11:00.993636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '048e645f18dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipo_local', sa.String(length=100), nullable=False),
    sa.Column('equipo_visitante', sa.String(length=100), nullable=False),
    sa.Column('bandera_local', sa.String(length=10), nullable=True),
    sa.Column('bandera_visitante', sa.String(length=10), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('fase', sa.Enum('grupos', 'dieciseisavos', 'octavos', 'cuartos', 'semifinal', 'tercer_puesto', 'final', name='fasepartido'), nullable=True),
    sa.Column('goles_local', sa.Integer(), nullable=True),
    sa.Column('goles_visitante', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'vivo', 'finalizado', name='estadopartido'), nullable=True),
    sa.Column('cierre_pronosticos', sa.DateTime(), nullable=False),
    sa.Column('clasificado_local', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('es_pro', sa.Boolean(), nullable=False),
    sa.Column('pro_activado_en', sa.DateTime(), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('proveedor_auth', sa.Enum('local', 'google', name='proveedorauth'), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('grupos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creador_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('codigo_invitacion', sa.String(length=10), nullable=False),
    sa.Column('max_participantes', sa.Integer(), nullable=True),
    sa.Column('premio_valor', sa.Float(), nullable=True),
    sa.Column('premio_moneda', sa.String(length=10), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('activo', 'cerrado', name='estadogrupo'), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('pts_marcador_exacto', sa.Integer(), nullable=True),
    sa.Column('pts_ganador', sa.Integer(), nullable=True),
    sa.Column('pts_empate', sa.Integer(), nullable=True),
    sa.Column('pts_gol', sa.Integer(), nullable=True),
    sa.Column('pts_prediccion_unica', sa.Integer(), nullable=True),
    sa.Column('bono_dieciseisavos', sa.Integer(), nullable=True),
    sa.Column('bono_octavos', sa.Integer(), nullable=True),
    sa.Column('bono_cuartos', sa.Integer(), nullable=True),
    sa.Column('bono_semifinales', sa.Integer(), nullable=True),
    sa.Column('bono_final', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_codigo_invitacion'), 'grupos', ['codigo_invitacion'], unique=True)
    op.create_table('pagos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('monto_usd', sa.Float(), nullable=False),
    sa.Column('estado', sa.Enum('pending', 'completado', 'fallido', name='estadopago'), nullable=True),
    sa.Column('pagado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    op.create_table('sugerencias_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('partido_id', sa.UUID(), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=False),
    sa.Column('goles_visitante', sa.Integer(), nullable=False),
    sa.Column('confianza', sa.Float(), nullable=False),
    sa.Column('generado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('partido_id')
    )
    op.create_table('grupo_participantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'player', name='rolgrupo'), nullable=True),
    sa.Column('total_puntos', sa.Integer(), nullable=True),
    sa.Column('posicion', sa.Integer(), nullable=True),
    sa.Column('unido_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grupo_id', 'user_id', name='uq_grupo_user')
    )
    op.create_table('pronosticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('partido_id', sa.UUID(), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('goles_local', sa.Integer(), nullable=False),
    sa.Column('goles_visitante', sa.Integer(), nullable=False),
    sa.Column('puntos_obtenidos', sa.Integer(), nullable=True),
    sa.Column('fue_autocompletado', sa.Boolean(), nullable=True),
    sa.Column('fuente', sa.Enum('manual', 'ia', name='fuentepronostico'), nullable=True),
    sa.Column('registrado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'partido_id', 'grupo_id', name='uq_pronostico')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pronosticos')
    op.drop_table('grupo_participantes')
    op.drop_table('sugerencias_ia')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_grupos_codigo_invitacion'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('partidos')
    # ### end Alembic commands ###