"""Add pro_expira_en to users

Revision ID: 448d8038d5ed
Revises: 048e645f18dd
Create Date: 2026-05-01 21:07:09.633583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '448d8038d5ed'
down_revision: Union[str, None] = '048e645f18dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_expira_en', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pro_expira_en')
    # ### end Alembic commands ###